service:
  type: ClusterIP
  ports:
    port: 8080
    targetPort: 8080
    name: metrics

replica_count: 2

containers:
  image_name: flask-app
  image_tag: 0.1.2
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

serviceMonitor:
  enabled: true
  namespace: monitoring
