apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}-deployment
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.service.ports.name | quote }}
    #prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}
      name: {{ .Values.service.ports.name | quote }}
  selector:
    app: {{ .Release.Name }}-deployment
